version: '3.4'

services:
  reactaspcrudbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - C:\Users\rithika.ab\AppData\Roaming\Microsoft\UserSecrets
      - C:\Users\rithika.ab\AppData\Roaming\ASP.NET\Https
